/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lckiosk;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author nexot
 */
public class Balance extends javax.swing.JFrame {

    /**
     * Creates new form Balance
     */
    Accounts acc;
    public Balance() {
        initComponents();
    }
    public Balance(Accounts acc) {
        initComponents();
        this.acc = acc;
        ImageIcon icon = new ImageIcon("src\\lckiosk\\icon.png");
        this.setIconImage(icon.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PhoneNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pin = new javax.swing.JTextField();
        proceedInput = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(330, 392));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("LOVE CASH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(105, 60, 129, 32);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("BALANCE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(128, 98, 75, 25);

        jLabel3.setText("Enter Mobile Phone: +63");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(17, 197, 160, 16);

        PhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberActionPerformed(evt);
            }
        });
        getContentPane().add(PhoneNumber);
        PhoneNumber.setBounds(160, 194, 117, 22);

        jLabel4.setText("Enter PIN:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(97, 228, 60, 16);

        pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinActionPerformed(evt);
            }
        });
        getContentPane().add(pin);
        pin.setBounds(160, 225, 71, 22);

        proceedInput.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        proceedInput.setText("OKAY");
        proceedInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedInputActionPerformed(evt);
            }
        });
        getContentPane().add(proceedInput);
        proceedInput.setBounds(123, 300, 72, 36);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lckiosk/bg.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 340, 390);

        setSize(new java.awt.Dimension(344, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void proceedInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedInputActionPerformed
        String phoneNumber = PhoneNumber.getText();
        String pinInput = pin.getText();
        
        
        if (acc.getAccountList().contains(phoneNumber) && acc.getAccountList().contains(pinInput)){
            JOptionPane.showMessageDialog(null, "Login Successfully");
            JOptionPane.showMessageDialog(null, "your Balance is: " + acc.getAccount(2));   
            RhomeIn ri = new RhomeIn(acc);
            ri.setVisible(true);
            dispose();
        }else {
            JOptionPane.showMessageDialog(null, "Invalid Mobile Phone or Password");
        }  
    }                                        

    private void pinInputActionPerformed() {                                         
    }//GEN-LAST:event_proceedInputActionPerformed

    private void pinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinActionPerformed

    private void PhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Balance().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PhoneNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField pin;
    private javax.swing.JButton proceedInput;
    // End of variables declaration//GEN-END:variables

    
}
