/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lckiosk;

import javax.swing.ImageIcon;

/**
 *
 * @author nexot
 */
public class Option extends javax.swing.JFrame {
    Accounts acc;
    /**
     * Creates new form Option
     */
    
    public Option() {
        initComponents();
    }
    public Option(Accounts acc){
        initComponents();
        this.acc = acc;
        ImageIcon icon = new ImageIcon("src\\lckiosk\\icon.png");
        this.setIconImage(icon.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cashInButton = new javax.swing.JButton();
        cashOutButton = new javax.swing.JButton();
        balanceButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(330, 392));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("LOVE CASH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(104, 62, 129, 32);

        cashInButton.setText("CASH IN");
        cashInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashInButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cashInButton);
        cashInButton.setBounds(50, 290, 100, 34);

        cashOutButton.setText("CASH OUT");
        cashOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashOutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cashOutButton);
        cashOutButton.setBounds(50, 240, 100, 34);

        balanceButton.setText("BALANCE");
        balanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(balanceButton);
        balanceButton.setBounds(180, 240, 100, 34);

        homeButton.setText("HOME");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton);
        homeButton.setBounds(180, 290, 100, 34);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lckiosk/bg.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(330, 392));
        jLabel2.setMinimumSize(new java.awt.Dimension(330, 392));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 330, 392);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cashInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashInButtonActionPerformed
        // TODO add your handling code her
       CashIn ci = new CashIn(acc);
       ci.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_cashInButtonActionPerformed

    private void cashOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashOutButtonActionPerformed
        // TODO add your handling code here:
       CashOut co = new CashOut(acc);
       System.out.println(acc.getAccount(2));
       co.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_cashOutButtonActionPerformed

    private void balanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceButtonActionPerformed
        // TODO add your handling code here:
        Balance b = new Balance(acc);
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_balanceButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        Home h = new Home(acc);
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeButtonActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Option().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balanceButton;
    private javax.swing.JButton cashInButton;
    private javax.swing.JButton cashOutButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
